// For Vaccine
export const ADD_VACCINES_TOSTORE = "VACCINE.ADD_VACCINES_TOSTORE";

// For Hospital
export const ADD_HOSPITALS_TOSTORE = "HOSPITAL.ADD_HOSPITALS_TOSTORE";
export const ADD_CHARGE = "HOSPITAL.ADD_CHARGE";