// For Vaccine
export const ADD_VACCINES_TOSTORE = "VACCINE.ADD_VACCINES_TOSTORE";

// For Hospital
export const ADD_HOSPITALS_TOSTORE = "HOSPITAL.ADD_HOSPITALS_TOSTORE";
export const ADD_CHARGE = "HOSPITAL.ADD_CHARGE";

//For User
export const AddUserToStore = "USER.ADD_USER_TOSTORE";
export const SIGN_OUT_USER = "USER.SIGN_OUT_USER";
export const SIGN_IN_USER = "USER.SIGN_IN_USER";

//For Appointment
export const ADD_APPOINTMENTS_TOSTORE = "APPOINTMENT.ADD_APPOINTMENTS_TOSTORE";